### ISSUE TITLE
Incompatible scipy version

### ISSUE THREAD

**Issue by JoelPasvolsky** [dwavesystems/penaltymodel#130]
**Description**
If you `pip install dwavebinarycsp` and then build `penaltymodel-maxgap`, running any `dwavebinarycsp.stich()` fails for `scipy==1.4.1`:

```
decorator==4.4.2
dimod==0.9.11
dwave-networkx==0.8.4
dwavebinarycsp==0.1.2
homebase==1.0.1
networkx==2.5.1
numpy==1.20.2
penaltymodel==0.16.4
penaltymodel-cache==0.4.3
penaltymodel-lp==0.1.4
penaltymodel-maxgap==0.5.4
PySMT==0.8.0
scipy==1.4.1
six==1.16.0
```

For example:

```
>>> import dwavebinarycsp as dbc
>>> csp = dbc.factories.random_2in4sat(8, 4)
>>> dbc.stitch(csp)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>

<see referenced issue for more>
```

Upgrading scipy solves the problem

**To Reproduce**
As described above

**Expected behavior**
No errors

**Environment:**
 - OS: Ubuntu 16.0 and Win10 and colab
 - Python version: 3.7.0

**Additional context**
See https://github.com/dwave-examples/factoring-notebook/issues/16
I was unable to reproduce using `pip install` instead of build penaltymodel from source. I noticed that colab builds from source and managed to reproduce the problem in both unix and Window OSs.

**Comment by arcondello** [comment]
@JoelPasvolsky , were you ever able to resolve this issue? Can we close it?

**Comment by JoelPasvolsky** [comment]
Looks like [this dwavebinarycsp commit](https://github.com/dwavesystems/dwavebinarycsp/commit/847b89af4053a7a379bca16d2705b56db9a71061) updated [penaltymodel requirements](https://github.com/dwavesystems/penaltymodel/blob/master/requirements.txt) to use `scipy==1.7.3` so that should fix it
