### ISSUE TITLE
Images for README

### ISSUE THREAD

**Issue by arcondello** [dwavesystems/penaltymodel#21]
![and_table](https://user-images.githubusercontent.com/8395238/34234533-8da5a364-e5a0-11e7-9d9f-068b4ab3a0fd.png)
![and_caption](https://user-images.githubusercontent.com/8395238/34234542-986d76c8-e5a0-11e7-8954-4ef942b4f079.png)
![gap](https://user-images.githubusercontent.com/8395238/34234545-9c93e5f2-e5a0-11e7-8792-5777a5c4303e.png)

**Comment by m3ller** [comment]
This was merged with commit 04c390fed47d38673f646fed0a6706d7b733e56e
