### ISSUE TITLE
PySMT version conflict

### ISSUE THREAD

**Issue by tsphillips** [dwavesystems/penaltymodel#61]
**Description**
I use pysmt version 0.7.5. penaltymodel complains.

```
setup_requires = ['pysmt==0.7.0']

install_requires = ['dimod>=0.6.3,<0.8.0',
                    'dwave_networkx>=0.6.0,<0.7.0',
                    'penaltymodel>=0.15.0,<0.16.0',
                    'pysmt==0.7.0',
                    'six>=1.11.0,<2.0.0',
                    ]
```

**To Reproduce**
Upgrade to pysmt > 0.7.0.

**Expected behavior**
I want penaltymodel to live happily with pysmt 0.7.5.

**Environment:**
- Python 3.7
- pip version 18.0

**Additional context**
This came up while trying to troubleshoot a test for dwavebinarycsp, in which the stitch() call produced the error:
`pysmt.exceptions.NoSolverAvailableError: No Solver is available`

After a comprehensive package update, now the dwavebinarycsp test produces the error:
`pkg_resources.VersionConflict: (PySMT 0.7.5 (/usr/local/lib/python3.7/site-packages), Requirement.parse('pysmt==0.7.0'))`

**Comment by arcondello** [comment]
Hi @tsphillips ,

We've had issues with pysmt 0.7.5, specifically it changes the way that smt solvers are added to the python path. @randomir has made a PR to help address this issue, see https://github.com/pysmt/pysmt/pull/517 but it will not be available until the next pysmt deploy.

**Comment by arcondello** [comment]
We recommend using `penaltymodel-mip` unless you are using 32bit python and/or python3.4

**Comment by arcondello** [comment]
As of version [1.0.0](https://github.com/dwavesystems/penaltymodel/releases/tag/1.0.0) we use SciPy rather than PySMIT so this is no longer relevant.
