### ISSUE TITLE
Misc Documentation Fixes

### ISSUE THREAD

**Issue by arcondello** [dwavesystems/penaltymodel#7]
Vartype definition is displayed twice

**Comment by arcondello** [comment]
The adj attribute needs better explanation in BinaryQuadraticModel
as_ising and as_qubo return type  in BinaryQuadraticModel
Explain exception subclass structure

**Comment by arcondello** [comment]
@orenshk 
Any other doc issues add them here. Thanks!

**Comment by arcondello** [comment]
@aidanproy Putting these here for posterity and so that I don't lose track of them.

The documentation should define a penalty model (and Ising model, QUBO, 
feasible configuration, etc.) more precisely or give references

- I wonder if "Boolean" would a better description of the {0,1} VarType 
than "Binary", given that a "binary quadratic model" is also allowed to 
be of vartype "spin"...

- when "Vartype" is defined it would be helpful if the documentation 
stated up front that "QUBO" is associated with "Boolean/Binary" and 
"Ising" is associated with "spin"

- when Specification class is defined it would be helpful if the 
documentation stated up front what it's used for (input to a penalty 
model factory)

- typo in penaltymodel->decision_variables doc: "case" should be "cast"

- in BinaryQuadraticModel, offset should be defined (is it ground state 
energy?)

- A single energy range (eg. [-2,2]) would be a useful way of inputting 
Specification.linear_energy_ranges in addition to a dictionary of energy 
ranges. Same for quadratic_energy_ranges.

- It might be useful for penalty models to have an extra "graph 
structure" flag of some sort, like "complete" or "chimera"?

- Will dimod and penaltymodel eventually use to same notion of 
BinaryQuadraticModel?

- I'd like to see a "verifyRelationIsingModel" type function here rather 
than in the factory modules

**Comment by orenshk** [comment]
What is the name of an 'edge' in a binary quadratic model? add this to the BinaryQuadraticModel class comment.

**Comment by orenshk** [comment]
Mention that decision variables must match the labels of the graph.
https://github.com/dwavesystems/penaltymodel/blob/01db8d5a6e75ee553d99c492ae028fbb18413d7d/penaltymodel/classes/penaltymodel.py#L58-L59

**Comment by arcondello** [comment]
- [ ] Vartype definition is displayed twice

**Comment by arcondello** [comment]
I believe all of these are addressed in 1.0.0 release.
